services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data:/data
      - ./src:/src
  compass:
    image: haohanyang/compass-web
    container_name: compass
    environment:
      - CW_MONGO_URI=mongodb://admin:password@mongodb:27017
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    links:
      - mongodb